services:
  ebpf-probe:
    build: .
    pid: "host"
    privileged: true
    network_mode: host
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
      - /lib/modules:/lib/modules:ro
      - /var/log/ebpf-game:/var/log/ebpf-game
    restart: unless-stopped
