version: '3.8'

services:
  ebpf-monitor:
    build: .
    privileged: true  # Required for eBPF access
    network_mode: host  # Access to host network for better kernel access
    volumes:
      - /sys:/sys:ro  # Read-only access to sysfs
      - /proc:/proc:ro  # Read-only access to procfs
      - /boot:/boot:ro  # Read-only access to boot for kernel headers
    environment:
      - GOOS=linux
      - GOARCH=amd64
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Alternative: run as root for eBPF access
    user: root 